# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/namotyl/Repos/hexapod

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/namotyl/Repos/hexapod

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/namotyl/Repos/hexapod/CMakeFiles /home/namotyl/Repos/hexapod//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/namotyl/Repos/hexapod/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hexapod

# Build rule for target.
hexapod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hexapod
.PHONY : hexapod

# fast build rule for target.
hexapod/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/build
.PHONY : hexapod/fast

src/HexapodApp.o: src/HexapodApp.cpp.o
.PHONY : src/HexapodApp.o

# target to build an object file
src/HexapodApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/HexapodApp.cpp.o
.PHONY : src/HexapodApp.cpp.o

src/HexapodApp.i: src/HexapodApp.cpp.i
.PHONY : src/HexapodApp.i

# target to preprocess a source file
src/HexapodApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/HexapodApp.cpp.i
.PHONY : src/HexapodApp.cpp.i

src/HexapodApp.s: src/HexapodApp.cpp.s
.PHONY : src/HexapodApp.s

# target to generate assembly for a file
src/HexapodApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/HexapodApp.cpp.s
.PHONY : src/HexapodApp.cpp.s

src/HexapodBody.o: src/HexapodBody.cpp.o
.PHONY : src/HexapodBody.o

# target to build an object file
src/HexapodBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/HexapodBody.cpp.o
.PHONY : src/HexapodBody.cpp.o

src/HexapodBody.i: src/HexapodBody.cpp.i
.PHONY : src/HexapodBody.i

# target to preprocess a source file
src/HexapodBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/HexapodBody.cpp.i
.PHONY : src/HexapodBody.cpp.i

src/HexapodBody.s: src/HexapodBody.cpp.s
.PHONY : src/HexapodBody.s

# target to generate assembly for a file
src/HexapodBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/HexapodBody.cpp.s
.PHONY : src/HexapodBody.cpp.s

src/Leg.o: src/Leg.cpp.o
.PHONY : src/Leg.o

# target to build an object file
src/Leg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/Leg.cpp.o
.PHONY : src/Leg.cpp.o

src/Leg.i: src/Leg.cpp.i
.PHONY : src/Leg.i

# target to preprocess a source file
src/Leg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/Leg.cpp.i
.PHONY : src/Leg.cpp.i

src/Leg.s: src/Leg.cpp.s
.PHONY : src/Leg.s

# target to generate assembly for a file
src/Leg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/Leg.cpp.s
.PHONY : src/Leg.cpp.s

src/TripodGait.o: src/TripodGait.cpp.o
.PHONY : src/TripodGait.o

# target to build an object file
src/TripodGait.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/TripodGait.cpp.o
.PHONY : src/TripodGait.cpp.o

src/TripodGait.i: src/TripodGait.cpp.i
.PHONY : src/TripodGait.i

# target to preprocess a source file
src/TripodGait.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/TripodGait.cpp.i
.PHONY : src/TripodGait.cpp.i

src/TripodGait.s: src/TripodGait.cpp.s
.PHONY : src/TripodGait.s

# target to generate assembly for a file
src/TripodGait.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hexapod.dir/build.make CMakeFiles/hexapod.dir/src/TripodGait.cpp.s
.PHONY : src/TripodGait.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hexapod"
	@echo "... src/HexapodApp.o"
	@echo "... src/HexapodApp.i"
	@echo "... src/HexapodApp.s"
	@echo "... src/HexapodBody.o"
	@echo "... src/HexapodBody.i"
	@echo "... src/HexapodBody.s"
	@echo "... src/Leg.o"
	@echo "... src/Leg.i"
	@echo "... src/Leg.s"
	@echo "... src/TripodGait.o"
	@echo "... src/TripodGait.i"
	@echo "... src/TripodGait.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

